#!/usr/bin/env bash
#
# stamp-backlinks.sh — inject backlinks into a freshly generated SDK.
#
# Two layers of backlinks are stamped by the SDK pipeline:
#   1. SPEC LEVEL: the OpenAPI `info`/`externalDocs` blocks are patched before
#      generation (see fetch-openapi-spec in sdks/.gitlab-ci.yml). Every
#      generator embeds `info` into package metadata, READMEs and code
#      comments, so the links travel into all ~100 SDKs automatically.
#   2. FILE LEVEL: this script merges the template header (badges) with the
#      generated README, keeps a copy as README.generated.md, and appends
#      a footer with License/Contributing/Security links + VERSION marker.
#
# Usage: stamp-backlinks.sh <generated_dir> <generator> <language> <version>
#
set -euo pipefail

OUT="${1:?usage: stamp-backlinks.sh <generated_dir> <generator> <language> <version>}"
GEN="${2:?missing generator}"
LANG_NAME="${3:?missing language}"
VERSION="${4:?missing version}"
REPO_INPUT="${5:-}"
if [ -n "${REPO_INPUT}" ]; then
  REPO="${REPO_INPUT}"
elif [ -n "${REPO:-}" ]; then
  REPO="${REPO}"
else
  REPO="$(basename "$(git -C "${OUT}" rev-parse --show-toplevel 2>/dev/null || echo "${OUT}")")"
  if [[ "${REPO}" == "." || "${REPO}" == "generated_dir" ]]; then REPO="simplebilly-${LANG_NAME,,}"; fi
fi

echo "${VERSION}" > "${OUT}/VERSION"

HEADER=$(
  cat <<EOF
# SimpleBilly ${LANG_NAME} SDK

[![Release](https://img.shields.io/github/v/release/simplebilly/${REPO}?label=release&logo=github)](https://github.com/simplebilly/${REPO}/releases)
[![CI](https://github.com/simplebilly/${REPO}/actions/workflows/release.yml/badge.svg)](https://github.com/simplebilly/${REPO}/actions/workflows/release.yml)
[![CodeQL](https://github.com/simplebilly/${REPO}/actions/workflows/codeql.yml/badge.svg)](https://github.com/simplebilly/${REPO}/actions/workflows/codeql.yml)
[![Scorecard](https://github.com/simplebilly/${REPO}/actions/workflows/scorecard.yml/badge.svg)](https://github.com/simplebilly/${REPO}/actions/workflows/scorecard.yml)
[![OpenSSF Scorecard](https://api.scorecard.dev/projects/github.com/simplebilly/${REPO}/badge)](https://scorecard.dev/viewer/?uri=github.com/simplebilly/${REPO})
[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](LICENSE)
[![Docs](https://img.shields.io/badge/docs-simplebilly.com-blue)](https://simplebilly.com/api/docs)

EOF
)

FOOTER=$(
  cat <<'EOF'

---

## SimpleBilly API SDK

This client was generated automatically from the [SimpleBilly OpenAPI specification](https://simplebilly.com/api/docs).

- **Homepage:** https://simplebilly.com
- **API documentation:** https://simplebilly.com/api/docs
- **OpenAPI specification:** https://api.simplebilly.com/openapi.json
- **SDK sources:** https://github.com/simplebilly

## Contributing

See [CONTRIBUTING.md](CONTRIBUTING.md) — do not edit generated code by hand.

## Security

See [SECURITY.md](SECURITY.md) for reporting vulnerabilities.

## License

[MIT](LICENSE) — Copyright (c) SimpleBilly GmbH.

SimpleBilly is the first bookkeeping, CRM, online shop and ERP that follows the mantra: "just do it"

*Generated by the SimpleBilly SDK pipeline — do not edit manually.*
EOF
)

if [ -f "${OUT}/README.md" ]; then
  # Keep pristine generated README for reference
  cp "${OUT}/README.md" "${OUT}/README.generated.md"
  GENERATED="$(cat "${OUT}/README.generated.md")"
  # If generated README already has our badges, keep it as-is + footer, else prepend header
  if grep -q "github.com/simplebilly" "${OUT}/README.generated.md"; then
    printf '%s\n%s\n' "${GENERATED}" "${FOOTER}" > "${OUT}/README.md"
  else
    printf '%s\n%s\n%s\n' "${HEADER}" "${GENERATED}" "${FOOTER}" > "${OUT}/README.md"
  fi
else
  printf '%s\n# SimpleBilly %s SDK\n\n%s\n' "${HEADER}" "${LANG_NAME}" "${FOOTER}" > "${OUT}/README.md"
  echo "${HEADER}${FOOTER}" > "${OUT}/README.generated.md" 2>/dev/null || true
fi

echo "[stamp] ${GEN}: README header/footer + VERSION=${VERSION} written"
