#!/usr/bin/env bash
#
# stamp-backlinks.sh — inject backlinks into a freshly generated SDK.
#
# Two layers of backlinks are stamped by the SDK pipeline:
#   1. SPEC LEVEL: the OpenAPI `info`/`externalDocs` blocks are patched before
#      generation (see fetch-openapi-spec in sdks/.gitlab-ci.yml). Every
#      generator embeds `info` into package metadata, READMEs and code
#      comments, so the links travel into all ~100 SDKs automatically.
#   2. FILE LEVEL: this script appends a backlink footer to the generated
#      README (kept as README.generated.md) and writes a VERSION marker.
#
# Usage: stamp-backlinks.sh <generated_dir> <generator> <language> <version>
#
set -euo pipefail

OUT="${1:?usage: stamp-backlinks.sh <generated_dir> <generator> <language> <version>}"
GEN="${2:?missing generator}"
LANG_NAME="${3:?missing language}"
VERSION="${4:?missing version}"

# Marker consumed by the report job / humans inspecting the artifact.
echo "${VERSION}" > "${OUT}/VERSION"

FOOTER=$(
  cat <<'EOF'

---

## SimpleBilly API SDK

This client was generated automatically from the [SimpleBilly OpenAPI specification](https://simplebilly.com/api/docs).

- **Homepage:** https://simplebilly.com
- **API documentation:** https://simplebilly.com/api/docs
- **OpenAPI specification:** https://simplebilly.com/api/v1/openapi.json
- **SDK sources:** https://github.com/simplebilly

SimpleBilly is the first bookkeeping, CRM, online shop and ERP that doesn't give a fuck — for companies
that want to do relevant stuff instead of bookkeeping and paying tax lawyers.

*Generated by the SimpleBilly SDK pipeline — do not edit manually.*
EOF
)

if [ -f "${OUT}/README.md" ]; then
  # Preserve the generator's own usage docs, then append our backlink block.
  cp "${OUT}/README.md" "${OUT}/README.generated.md"
  printf '\n%s\n' "${FOOTER}" >> "${OUT}/README.md"
else
  printf '# SimpleBilly %s SDK\n\n%s\n' "${LANG_NAME}" "${FOOTER}" > "${OUT}/README.md"
fi

echo "[stamp] ${GEN}: README backlinks + VERSION=${VERSION} written"
