const AbsenceApi = require('../apis/AbsenceApi');
const ActivityApi = require('../apis/ActivityApi');
const AdminApi = require('../apis/AdminApi');
const AiApi = require('../apis/AiApi');
const AnlageEksApi = require('../apis/AnlageEksApi');
const AnlageGApi = require('../apis/AnlageGApi');
const AnlageSApi = require('../apis/AnlageSApi');
const AttachmentApi = require('../apis/AttachmentApi');
const AttachmentVersionApi = require('../apis/AttachmentVersionApi');
const AuthApi = require('../apis/AuthApi');
const AutomationsApi = require('../apis/AutomationsApi');
const BankingApi = require('../apis/BankingApi');
const BillingApi = require('../apis/BillingApi');
const BomApi = require('../apis/BomApi');
const BookkeepingApi = require('../apis/BookkeepingApi');
const BudgetsApi = require('../apis/BudgetsApi');
const ComplianceTrainingApi = require('../apis/ComplianceTrainingApi');
const ContactApi = require('../apis/ContactApi');
const CouponApi = require('../apis/CouponApi');
const CreateSepaDirectDebitApi = require('../apis/CreateSepaDirectDebitApi');
const CreditNoteApi = require('../apis/CreditNoteApi');
const CustomerApi = require('../apis/CustomerApi');
const CustomerCommunicationApi = require('../apis/CustomerCommunicationApi');
const CustomerGroupApi = require('../apis/CustomerGroupApi');
const DatevApi = require('../apis/DatevApi');
const DatevImportApi = require('../apis/DatevImportApi');
const DeclarationApi = require('../apis/DeclarationApi');
const DeliveryAppointmentApi = require('../apis/DeliveryAppointmentApi');
const DeliveryDateApi = require('../apis/DeliveryDateApi');
const DeliveryNoteApi = require('../apis/DeliveryNoteApi');
const DownPaymentInvoiceApi = require('../apis/DownPaymentInvoiceApi');
const EbilanzApi = require('../apis/EbilanzApi');
const EmailTemplateApi = require('../apis/EmailTemplateApi');
const EmissionsApi = require('../apis/EmissionsApi');
const EmployeeApi = require('../apis/EmployeeApi');
const EuerApi = require('../apis/EuerApi');
const EventSubscriptionApi = require('../apis/EventSubscriptionApi');
const FristenApi = require('../apis/FristenApi');
const GdprApi = require('../apis/GdprApi');
const GenerateQrcodeApi = require('../apis/GenerateQrcodeApi');
const GenerateXrechnungApi = require('../apis/GenerateXrechnungApi');
const GewerbesteuerApi = require('../apis/GewerbesteuerApi');
const GewinnverwendungApi = require('../apis/GewinnverwendungApi');
const GezApi = require('../apis/GezApi');
const GobdExportApi = require('../apis/GobdExportApi');
const GoodsReceiptApi = require('../apis/GoodsReceiptApi');
const GroupFigureApi = require('../apis/GroupFigureApi');
const ImportRunnerApi = require('../apis/ImportRunnerApi');
const InstituteApi = require('../apis/InstituteApi');
const InstituteProfileApi = require('../apis/InstituteProfileApi');
const InventoryCountApi = require('../apis/InventoryCountApi');
const InventoryValueApi = require('../apis/InventoryValueApi');
const InvoiceApi = require('../apis/InvoiceApi');
const JobApplicationApi = require('../apis/JobApplicationApi');
const JobPostingApi = require('../apis/JobPostingApi');
const KonzernApi = require('../apis/KonzernApi');
const KostenVorschauApi = require('../apis/KostenVorschauApi');
const KstApi = require('../apis/KstApi');
const KycRecordApi = require('../apis/KycRecordApi');
const LeadApi = require('../apis/LeadApi');
const LegalDocumentApi = require('../apis/LegalDocumentApi');
const ListOpenItemsApi = require('../apis/ListOpenItemsApi');
const MarketplaceApiApi = require('../apis/MarketplaceApiApi');
const NotificationsApi = require('../apis/NotificationsApi');
const OffenlegungApi = require('../apis/OffenlegungApi');
const OnlineshopApi = require('../apis/OnlineshopApi');
const OrderApi = require('../apis/OrderApi');
const OrderConfirmationApi = require('../apis/OrderConfirmationApi');
const OssReportApi = require('../apis/OssReportApi');
const PackingApi = require('../apis/PackingApi');
const ParticipationApi = require('../apis/ParticipationApi');
const PaygapApi = require('../apis/PaygapApi');
const PaymentApi = require('../apis/PaymentApi');
const PaymentConditionApi = require('../apis/PaymentConditionApi');
const PaymentGatewayApi = require('../apis/PaymentGatewayApi');
const PayrollApi = require('../apis/PayrollApi');
const PeppolApi = require('../apis/PeppolApi');
const PlausibilityApi = require('../apis/PlausibilityApi');
const PosApi = require('../apis/PosApi');
const PostingCategoryApi = require('../apis/PostingCategoryApi');
const PriceTierApi = require('../apis/PriceTierApi');
const ProductApi = require('../apis/ProductApi');
const ProductAttributeApi = require('../apis/ProductAttributeApi');
const ProductCategoryApi = require('../apis/ProductCategoryApi');
const ProductVariantApi = require('../apis/ProductVariantApi');
const ProductionOrderApi = require('../apis/ProductionOrderApi');
const ProformaInvoiceApi = require('../apis/ProformaInvoiceApi');
const ProposeAssignmentsApi = require('../apis/ProposeAssignmentsApi');
const PublicReturnsApi = require('../apis/PublicReturnsApi');
const PurchaseOrderApi = require('../apis/PurchaseOrderApi');
const QuotationApi = require('../apis/QuotationApi');
const RecurringTemplateApi = require('../apis/RecurringTemplateApi');
const ReorderProposalApi = require('../apis/ReorderProposalApi');
const ReplenishmentApi = require('../apis/ReplenishmentApi');
const ReportsApi = require('../apis/ReportsApi');
const ReturnOrderApi = require('../apis/ReturnOrderApi');
const RfqApi = require('../apis/RfqApi');
const SearchApi = require('../apis/SearchApi');
const ServiceAssignmentApi = require('../apis/ServiceAssignmentApi');
const ServiceJobApi = require('../apis/ServiceJobApi');
const ShareholderApi = require('../apis/ShareholderApi');
const ShipmentApi = require('../apis/ShipmentApi');
const ShippingApi = require('../apis/ShippingApi');
const ShippingRuleApi = require('../apis/ShippingRuleApi');
const ShippingThresholdApi = require('../apis/ShippingThresholdApi');
const ShopApi = require('../apis/ShopApi');
const SilentPartnerApi = require('../apis/SilentPartnerApi');
const StilleApi = require('../apis/StilleApi');
const StockMovementApi = require('../apis/StockMovementApi');
const StockTransferApi = require('../apis/StockTransferApi');
const SuitabilityApi = require('../apis/SuitabilityApi');
const SupplierConditionApi = require('../apis/SupplierConditionApi');
const SupplierInvoiceApi = require('../apis/SupplierInvoiceApi');
const SupportChannelApi = require('../apis/SupportChannelApi');
const SupportTicketApi = require('../apis/SupportTicketApi');
const TaxApi = require('../apis/TaxApi');
const TenantSettingsApi = require('../apis/TenantSettingsApi');
const TicketMessageApi = require('../apis/TicketMessageApi');
const TimeEntriesApi = require('../apis/TimeEntriesApi');
const TrainingAssignmentApi = require('../apis/TrainingAssignmentApi');
const TrainingsApi = require('../apis/TrainingsApi');
const UserApi = require('../apis/UserApi');
const UserManagementApi = require('../apis/UserManagementApi');
const UstvaApi = require('../apis/UstvaApi');
const VoucherApi = require('../apis/VoucherApi');
const WarehouseApi = require('../apis/WarehouseApi');
const WarehouseStockApi = require('../apis/WarehouseStockApi');
const WebhooksApi = require('../apis/WebhooksApi');
const WorkflowsApi = require('../apis/WorkflowsApi');
const ZugferdApi = require('../apis/ZugferdApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction, createMiddleware } = require('../utils/utils');

const actions = {
    [AbsenceApi.createAbsence.key]: AbsenceApi.createAbsence,
    [AbsenceApi.deleteAbsence.key]: AbsenceApi.deleteAbsence,
    [AbsenceApi.getAbsence.key]: AbsenceApi.getAbsence,
    [AbsenceApi.getAbsences.key]: AbsenceApi.getAbsences,
    [AbsenceApi.updateAbsence.key]: AbsenceApi.updateAbsence,
    [ActivityApi.createActivity.key]: ActivityApi.createActivity,
    [ActivityApi.deleteActivity.key]: ActivityApi.deleteActivity,
    [ActivityApi.getActivity.key]: ActivityApi.getActivity,
    [ActivityApi.listActivities.key]: ActivityApi.listActivities,
    [ActivityApi.updateActivity.key]: ActivityApi.updateActivity,
    [ActivityApi.updateActivityStatus.key]: ActivityApi.updateActivityStatus,
    [AdminApi.triggerMirror.key]: AdminApi.triggerMirror,
    [AiApi.aiSuggestApi.key]: AiApi.aiSuggestApi,
    [AiApi.createWorkerApi.key]: AiApi.createWorkerApi,
    [AiApi.listWorkersApi.key]: AiApi.listWorkersApi,
    [AiApi.runWorkerApi.key]: AiApi.runWorkerApi,
    [AnlageEksApi.eksApi.key]: AnlageEksApi.eksApi,
    [AnlageGApi.anlageGApi.key]: AnlageGApi.anlageGApi,
    [AnlageSApi.anlageSApi.key]: AnlageSApi.anlageSApi,
    [AttachmentApi.attachmentRestore.key]: AttachmentApi.attachmentRestore,
    [AttachmentApi.createAttachment.key]: AttachmentApi.createAttachment,
    [AttachmentApi.deleteAttachment.key]: AttachmentApi.deleteAttachment,
    [AttachmentApi.getAttachment.key]: AttachmentApi.getAttachment,
    [AttachmentApi.listAttachments.key]: AttachmentApi.listAttachments,
    [AttachmentApi.saveAttachmentOcrText.key]: AttachmentApi.saveAttachmentOcrText,
    [AttachmentVersionApi.createAttachmentVersion.key]: AttachmentVersionApi.createAttachmentVersion,
    [AttachmentVersionApi.listAttachmentVersions.key]: AttachmentVersionApi.listAttachmentVersions,
    [AttachmentVersionApi.restoreAttachmentVersion.key]: AttachmentVersionApi.restoreAttachmentVersion,
    [AuthApi.acceptInvite.key]: AuthApi.acceptInvite,
    [AuthApi.forgotPassword.key]: AuthApi.forgotPassword,
    [AuthApi.login.key]: AuthApi.login,
    [AuthApi.logout.key]: AuthApi.logout,
    [AuthApi.magicLinkLogin.key]: AuthApi.magicLinkLogin,
    [AuthApi.magicLinkVerify.key]: AuthApi.magicLinkVerify,
    [AuthApi.register.key]: AuthApi.register,
    [AuthApi.resetPassword.key]: AuthApi.resetPassword,
    [AuthApi.totpEnable.key]: AuthApi.totpEnable,
    [AuthApi.totpSetup.key]: AuthApi.totpSetup,
    [AuthApi.verifyEmail.key]: AuthApi.verifyEmail,
    [AutomationsApi.listAutomations.key]: AutomationsApi.listAutomations,
    [AutomationsApi.triggerAutomation.key]: AutomationsApi.triggerAutomation,
    [AutomationsApi.updateAutomation.key]: AutomationsApi.updateAutomation,
    [BankingApi.bankLookupApi.key]: BankingApi.bankLookupApi,
    [BankingApi.bankTransactionsApi.key]: BankingApi.bankTransactionsApi,
    [BankingApi.hebesatzLookupApi.key]: BankingApi.hebesatzLookupApi,
    [BillingApi.getPlans.key]: BillingApi.getPlans,
    [BillingApi.getQuotaApi.key]: BillingApi.getQuotaApi,
    [BillingApi.getSubscriptionApi.key]: BillingApi.getSubscriptionApi,
    [BillingApi.getUsageApi.key]: BillingApi.getUsageApi,
    [BillingApi.paddleSubscriptionWebhook.key]: BillingApi.paddleSubscriptionWebhook,
    [BillingApi.putQuotaApi.key]: BillingApi.putQuotaApi,
    [BomApi.createBom.key]: BomApi.createBom,
    [BomApi.deleteBom.key]: BomApi.deleteBom,
    [BomApi.getBom.key]: BomApi.getBom,
    [BomApi.listBoms.key]: BomApi.listBoms,
    [BomApi.updateBom.key]: BomApi.updateBom,
    [BookkeepingApi.allocatePaymentApi.key]: BookkeepingApi.allocatePaymentApi,
    [BookkeepingApi.bwaReportApi.key]: BookkeepingApi.bwaReportApi,
    [BookkeepingApi.elsterStatusApi.key]: BookkeepingApi.elsterStatusApi,
    [BookkeepingApi.elsterValidateApi.key]: BookkeepingApi.elsterValidateApi,
    [BookkeepingApi.elsterXmlApi.key]: BookkeepingApi.elsterXmlApi,
    [BookkeepingApi.getCashflow.key]: BookkeepingApi.getCashflow,
    [BookkeepingApi.getLiquidity.key]: BookkeepingApi.getLiquidity,
    [BookkeepingApi.getOpenInvoicesApi.key]: BookkeepingApi.getOpenInvoicesApi,
    [BookkeepingApi.getVerfahrensdokumentation.key]: BookkeepingApi.getVerfahrensdokumentation,
    [BookkeepingApi.runDunningApi.key]: BookkeepingApi.runDunningApi,
    [BudgetsApi.budgetsApi.key]: BudgetsApi.budgetsApi,
    [BudgetsApi.upsertBudgetGoalApi.key]: BudgetsApi.upsertBudgetGoalApi,
    [ComplianceTrainingApi.createComplianceTraining.key]: ComplianceTrainingApi.createComplianceTraining,
    [ComplianceTrainingApi.deleteComplianceTraining.key]: ComplianceTrainingApi.deleteComplianceTraining,
    [ComplianceTrainingApi.getComplianceTraining.key]: ComplianceTrainingApi.getComplianceTraining,
    [ComplianceTrainingApi.getComplianceTrainings.key]: ComplianceTrainingApi.getComplianceTrainings,
    [ComplianceTrainingApi.updateComplianceTraining.key]: ComplianceTrainingApi.updateComplianceTraining,
    [ContactApi.contactSchema.key]: ContactApi.contactSchema,
    [ContactApi.contactTimeline.key]: ContactApi.contactTimeline,
    [ContactApi.createContact.key]: ContactApi.createContact,
    [ContactApi.deleteContact.key]: ContactApi.deleteContact,
    [ContactApi.getContact.key]: ContactApi.getContact,
    [ContactApi.listContacts.key]: ContactApi.listContacts,
    [ContactApi.salesVolume.key]: ContactApi.salesVolume,
    [ContactApi.updateContact.key]: ContactApi.updateContact,
    [CouponApi.couponRestore.key]: CouponApi.couponRestore,
    [CouponApi.createCoupon.key]: CouponApi.createCoupon,
    [CouponApi.deleteCoupon.key]: CouponApi.deleteCoupon,
    [CouponApi.getCoupon.key]: CouponApi.getCoupon,
    [CouponApi.listCoupons.key]: CouponApi.listCoupons,
    [CouponApi.updateCoupon.key]: CouponApi.updateCoupon,
    [CreateSepaDirectDebitApi.createSepaDirectDebitApi.key]: CreateSepaDirectDebitApi.createSepaDirectDebitApi,
    [CreditNoteApi.createCreditNote.key]: CreditNoteApi.createCreditNote,
    [CreditNoteApi.downloadCreditNotePdf.key]: CreditNoteApi.downloadCreditNotePdf,
    [CreditNoteApi.getCreditNote.key]: CreditNoteApi.getCreditNote,
    [CreditNoteApi.listCreditNotes.key]: CreditNoteApi.listCreditNotes,
    [CustomerApi.createCustomer.key]: CustomerApi.createCustomer,
    [CustomerApi.customerRestore.key]: CustomerApi.customerRestore,
    [CustomerApi.deleteCustomer.key]: CustomerApi.deleteCustomer,
    [CustomerApi.getCustomer.key]: CustomerApi.getCustomer,
    [CustomerApi.getCustomers.key]: CustomerApi.getCustomers,
    [CustomerApi.updateCustomer.key]: CustomerApi.updateCustomer,
    [CustomerCommunicationApi.createCommunication.key]: CustomerCommunicationApi.createCommunication,
    [CustomerCommunicationApi.customercommunicationRestore.key]: CustomerCommunicationApi.customercommunicationRestore,
    [CustomerCommunicationApi.deleteCommunication.key]: CustomerCommunicationApi.deleteCommunication,
    [CustomerCommunicationApi.getCommunication.key]: CustomerCommunicationApi.getCommunication,
    [CustomerCommunicationApi.getContactHistory.key]: CustomerCommunicationApi.getContactHistory,
    [CustomerCommunicationApi.listCommunications.key]: CustomerCommunicationApi.listCommunications,
    [CustomerCommunicationApi.updateCommunication.key]: CustomerCommunicationApi.updateCommunication,
    [CustomerGroupApi.addGroupMembers.key]: CustomerGroupApi.addGroupMembers,
    [CustomerGroupApi.createCustomerGroup.key]: CustomerGroupApi.createCustomerGroup,
    [CustomerGroupApi.deleteCustomerGroup.key]: CustomerGroupApi.deleteCustomerGroup,
    [CustomerGroupApi.getCustomerGroup.key]: CustomerGroupApi.getCustomerGroup,
    [CustomerGroupApi.listCustomerGroups.key]: CustomerGroupApi.listCustomerGroups,
    [CustomerGroupApi.updateCustomerGroup.key]: CustomerGroupApi.updateCustomerGroup,
    [DatevApi.datevExportApi.key]: DatevApi.datevExportApi,
    [DatevApi.datevPreviewApi.key]: DatevApi.datevPreviewApi,
    [DatevImportApi.datevImportApi.key]: DatevImportApi.datevImportApi,
    [DeclarationApi.createDeclaration.key]: DeclarationApi.createDeclaration,
    [DeclarationApi.declarationRestore.key]: DeclarationApi.declarationRestore,
    [DeclarationApi.deleteDeclaration.key]: DeclarationApi.deleteDeclaration,
    [DeclarationApi.getDeclaration.key]: DeclarationApi.getDeclaration,
    [DeclarationApi.getDeclarations.key]: DeclarationApi.getDeclarations,
    [DeclarationApi.updateDeclaration.key]: DeclarationApi.updateDeclaration,
    [DeliveryAppointmentApi.createDeliveryAppointment.key]: DeliveryAppointmentApi.createDeliveryAppointment,
    [DeliveryAppointmentApi.deleteDeliveryAppointment.key]: DeliveryAppointmentApi.deleteDeliveryAppointment,
    [DeliveryAppointmentApi.getDeliveryAppointment.key]: DeliveryAppointmentApi.getDeliveryAppointment,
    [DeliveryAppointmentApi.getPublicDeliveryAppointmentStatus.key]: DeliveryAppointmentApi.getPublicDeliveryAppointmentStatus,
    [DeliveryAppointmentApi.listDeliveryAppointments.key]: DeliveryAppointmentApi.listDeliveryAppointments,
    [DeliveryAppointmentApi.requestPublicDeliveryAppointment.key]: DeliveryAppointmentApi.requestPublicDeliveryAppointment,
    [DeliveryAppointmentApi.updateDeliveryAppointment.key]: DeliveryAppointmentApi.updateDeliveryAppointment,
    [DeliveryAppointmentApi.updateDeliveryAppointmentStatus.key]: DeliveryAppointmentApi.updateDeliveryAppointmentStatus,
    [DeliveryDateApi.createDeliveryDate.key]: DeliveryDateApi.createDeliveryDate,
    [DeliveryDateApi.deleteDeliveryDate.key]: DeliveryDateApi.deleteDeliveryDate,
    [DeliveryDateApi.getDeliveryDate.key]: DeliveryDateApi.getDeliveryDate,
    [DeliveryDateApi.getDeliveryPerformance.key]: DeliveryDateApi.getDeliveryPerformance,
    [DeliveryDateApi.listDeliveryDates.key]: DeliveryDateApi.listDeliveryDates,
    [DeliveryDateApi.updateDeliveryDate.key]: DeliveryDateApi.updateDeliveryDate,
    [DeliveryDateApi.updateDeliveryDateStatus.key]: DeliveryDateApi.updateDeliveryDateStatus,
    [DeliveryNoteApi.createDeliveryNote.key]: DeliveryNoteApi.createDeliveryNote,
    [DeliveryNoteApi.deleteDeliveryNote.key]: DeliveryNoteApi.deleteDeliveryNote,
    [DeliveryNoteApi.deliverynoteRestore.key]: DeliveryNoteApi.deliverynoteRestore,
    [DeliveryNoteApi.downloadDeliveryNotePdf.key]: DeliveryNoteApi.downloadDeliveryNotePdf,
    [DeliveryNoteApi.getDeliveryNote.key]: DeliveryNoteApi.getDeliveryNote,
    [DeliveryNoteApi.listDeliveryNotes.key]: DeliveryNoteApi.listDeliveryNotes,
    [DeliveryNoteApi.pursueDeliveryNote.key]: DeliveryNoteApi.pursueDeliveryNote,
    [DownPaymentInvoiceApi.downloadDownPaymentInvoicePdf.key]: DownPaymentInvoiceApi.downloadDownPaymentInvoicePdf,
    [DownPaymentInvoiceApi.getDownPaymentInvoice.key]: DownPaymentInvoiceApi.getDownPaymentInvoice,
    [DownPaymentInvoiceApi.listDownPaymentInvoices.key]: DownPaymentInvoiceApi.listDownPaymentInvoices,
    [EbilanzApi.ebilanzReportApi.key]: EbilanzApi.ebilanzReportApi,
    [EbilanzApi.ebilanzXbrlExportApi.key]: EbilanzApi.ebilanzXbrlExportApi,
    [EmailTemplateApi.createEmailTemplate.key]: EmailTemplateApi.createEmailTemplate,
    [EmailTemplateApi.deleteEmailTemplate.key]: EmailTemplateApi.deleteEmailTemplate,
    [EmailTemplateApi.getEmailTemplate.key]: EmailTemplateApi.getEmailTemplate,
    [EmailTemplateApi.listEmailTemplates.key]: EmailTemplateApi.listEmailTemplates,
    [EmailTemplateApi.renderEmailTemplate.key]: EmailTemplateApi.renderEmailTemplate,
    [EmailTemplateApi.updateEmailTemplate.key]: EmailTemplateApi.updateEmailTemplate,
    [EmissionsApi.createEmissionEntryApi.key]: EmissionsApi.createEmissionEntryApi,
    [EmissionsApi.createEmissionTargetApi.key]: EmissionsApi.createEmissionTargetApi,
    [EmissionsApi.deleteEmissionEntryApi.key]: EmissionsApi.deleteEmissionEntryApi,
    [EmissionsApi.deleteEmissionTargetApi.key]: EmissionsApi.deleteEmissionTargetApi,
    [EmissionsApi.emissionsEntriesApi.key]: EmissionsApi.emissionsEntriesApi,
    [EmissionsApi.emissionsExportApi.key]: EmissionsApi.emissionsExportApi,
    [EmissionsApi.emissionsFactorsApi.key]: EmissionsApi.emissionsFactorsApi,
    [EmissionsApi.emissionsReportApi.key]: EmissionsApi.emissionsReportApi,
    [EmissionsApi.emissionsTargetsApi.key]: EmissionsApi.emissionsTargetsApi,
    [EmployeeApi.createEmployee.key]: EmployeeApi.createEmployee,
    [EmployeeApi.deleteEmployee.key]: EmployeeApi.deleteEmployee,
    [EmployeeApi.employeeRestore.key]: EmployeeApi.employeeRestore,
    [EmployeeApi.getEmployee.key]: EmployeeApi.getEmployee,
    [EmployeeApi.getEmployeePayrollSummary.key]: EmployeeApi.getEmployeePayrollSummary,
    [EmployeeApi.getEmployees.key]: EmployeeApi.getEmployees,
    [EmployeeApi.updateEmployee.key]: EmployeeApi.updateEmployee,
    [EuerApi.euerApi.key]: EuerApi.euerApi,
    [EuerApi.euerKategorienApi.key]: EuerApi.euerKategorienApi,
    [EventSubscriptionApi.createEventSubscription.key]: EventSubscriptionApi.createEventSubscription,
    [EventSubscriptionApi.deleteEventSubscription.key]: EventSubscriptionApi.deleteEventSubscription,
    [EventSubscriptionApi.listEventSubscriptions.key]: EventSubscriptionApi.listEventSubscriptions,
    [FristenApi.fristenApi.key]: FristenApi.fristenApi,
    [GdprApi.acceptDpa.key]: GdprApi.acceptDpa,
    [GdprApi.accountErasure.key]: GdprApi.accountErasure,
    [GdprApi.erasureContact.key]: GdprApi.erasureContact,
    [GdprApi.exportContactData.key]: GdprApi.exportContactData,
    [GdprApi.exportGdpr.key]: GdprApi.exportGdpr,
    [GdprApi.getDpa.key]: GdprApi.getDpa,
    [GenerateQrcodeApi.generateQrcodeApi.key]: GenerateQrcodeApi.generateQrcodeApi,
    [GenerateXrechnungApi.generateXrechnungApi.key]: GenerateXrechnungApi.generateXrechnungApi,
    [GewerbesteuerApi.gewerbesteuerApi.key]: GewerbesteuerApi.gewerbesteuerApi,
    [GewinnverwendungApi.gewinnverwendungApi.key]: GewinnverwendungApi.gewinnverwendungApi,
    [GewinnverwendungApi.gewinnverwendungExportApi.key]: GewinnverwendungApi.gewinnverwendungExportApi,
    [GezApi.gezApi.key]: GezApi.gezApi,
    [GobdExportApi.buchhalterCsvApi.key]: GobdExportApi.buchhalterCsvApi,
    [GobdExportApi.gobdExportApi.key]: GobdExportApi.gobdExportApi,
    [GoodsReceiptApi.createGoodsReceipt.key]: GoodsReceiptApi.createGoodsReceipt,
    [GoodsReceiptApi.deleteGoodsReceipt.key]: GoodsReceiptApi.deleteGoodsReceipt,
    [GoodsReceiptApi.getGoodsReceipt.key]: GoodsReceiptApi.getGoodsReceipt,
    [GoodsReceiptApi.listGoodsReceipts.key]: GoodsReceiptApi.listGoodsReceipts,
    [GroupFigureApi.createGroupFigure.key]: GroupFigureApi.createGroupFigure,
    [GroupFigureApi.deleteGroupFigure.key]: GroupFigureApi.deleteGroupFigure,
    [GroupFigureApi.getGroupFigure.key]: GroupFigureApi.getGroupFigure,
    [GroupFigureApi.getGroupFigures.key]: GroupFigureApi.getGroupFigures,
    [GroupFigureApi.updateGroupFigure.key]: GroupFigureApi.updateGroupFigure,
    [ImportRunnerApi.getImportStatus.key]: ImportRunnerApi.getImportStatus,
    [ImportRunnerApi.startImport.key]: ImportRunnerApi.startImport,
    [ImportRunnerApi.testImportConnection.key]: ImportRunnerApi.testImportConnection,
    [InstituteApi.instituteStatusApi.key]: InstituteApi.instituteStatusApi,
    [InstituteProfileApi.getInstituteProfile.key]: InstituteProfileApi.getInstituteProfile,
    [InstituteProfileApi.updateInstituteProfile.key]: InstituteProfileApi.updateInstituteProfile,
    [InventoryCountApi.createInventoryCount.key]: InventoryCountApi.createInventoryCount,
    [InventoryCountApi.deleteInventoryCount.key]: InventoryCountApi.deleteInventoryCount,
    [InventoryCountApi.generateInventoryCount.key]: InventoryCountApi.generateInventoryCount,
    [InventoryCountApi.getInventoryCount.key]: InventoryCountApi.getInventoryCount,
    [InventoryCountApi.listInventoryCounts.key]: InventoryCountApi.listInventoryCounts,
    [InventoryCountApi.updateInventoryCount.key]: InventoryCountApi.updateInventoryCount,
    [InventoryCountApi.updateInventoryCountStatus.key]: InventoryCountApi.updateInventoryCountStatus,
    [InventoryValueApi.getInventoryValueApi.key]: InventoryValueApi.getInventoryValueApi,
    [InventoryValueApi.recordInventoryValueApi.key]: InventoryValueApi.recordInventoryValueApi,
    [InvoiceApi.createInvoice.key]: InvoiceApi.createInvoice,
    [InvoiceApi.deleteInvoice.key]: InvoiceApi.deleteInvoice,
    [InvoiceApi.downloadInvoicePdf.key]: InvoiceApi.downloadInvoicePdf,
    [InvoiceApi.getInvoice.key]: InvoiceApi.getInvoice,
    [InvoiceApi.getInvoicePdfUrl.key]: InvoiceApi.getInvoicePdfUrl,
    [InvoiceApi.getInvoices.key]: InvoiceApi.getInvoices,
    [InvoiceApi.invoiceRestore.key]: InvoiceApi.invoiceRestore,
    [InvoiceApi.updateInvoice.key]: InvoiceApi.updateInvoice,
    [JobApplicationApi.applyPublic.key]: JobApplicationApi.applyPublic,
    [JobApplicationApi.deleteJobApplication.key]: JobApplicationApi.deleteJobApplication,
    [JobApplicationApi.downloadCv.key]: JobApplicationApi.downloadCv,
    [JobApplicationApi.getJobApplication.key]: JobApplicationApi.getJobApplication,
    [JobApplicationApi.inboundEmail.key]: JobApplicationApi.inboundEmail,
    [JobApplicationApi.listJobApplications.key]: JobApplicationApi.listJobApplications,
    [JobApplicationApi.listPublicPostings.key]: JobApplicationApi.listPublicPostings,
    [JobApplicationApi.scoreJobApplication.key]: JobApplicationApi.scoreJobApplication,
    [JobApplicationApi.updateJobApplicationStatus.key]: JobApplicationApi.updateJobApplicationStatus,
    [JobPostingApi.createJobPosting.key]: JobPostingApi.createJobPosting,
    [JobPostingApi.deleteJobPosting.key]: JobPostingApi.deleteJobPosting,
    [JobPostingApi.getJobPosting.key]: JobPostingApi.getJobPosting,
    [JobPostingApi.listJobPostings.key]: JobPostingApi.listJobPostings,
    [JobPostingApi.updateJobPosting.key]: JobPostingApi.updateJobPosting,
    [KonzernApi.konzernExportApi.key]: KonzernApi.konzernExportApi,
    [KonzernApi.konzernStatusApi.key]: KonzernApi.konzernStatusApi,
    [KostenVorschauApi.kostenVorschauApi.key]: KostenVorschauApi.kostenVorschauApi,
    [KstApi.kstApi.key]: KstApi.kstApi,
    [KycRecordApi.createKycRecord.key]: KycRecordApi.createKycRecord,
    [KycRecordApi.deleteKycRecord.key]: KycRecordApi.deleteKycRecord,
    [KycRecordApi.getKycRecord.key]: KycRecordApi.getKycRecord,
    [KycRecordApi.getKycRecords.key]: KycRecordApi.getKycRecords,
    [KycRecordApi.updateKycRecord.key]: KycRecordApi.updateKycRecord,
    [LeadApi.listLeadsApi.key]: LeadApi.listLeadsApi,
    [LeadApi.updateLeadApi.key]: LeadApi.updateLeadApi,
    [LegalDocumentApi.getLegalDocuments.key]: LegalDocumentApi.getLegalDocuments,
    [LegalDocumentApi.resetLegalDocuments.key]: LegalDocumentApi.resetLegalDocuments,
    [LegalDocumentApi.upsertLegalDocuments.key]: LegalDocumentApi.upsertLegalDocuments,
    [ListOpenItemsApi.listOpenItemsApi.key]: ListOpenItemsApi.listOpenItemsApi,
    [MarketplaceApiApi.createConnectionApi.key]: MarketplaceApiApi.createConnectionApi,
    [MarketplaceApiApi.deleteConnectionApi.key]: MarketplaceApiApi.deleteConnectionApi,
    [MarketplaceApiApi.getConnectionApi.key]: MarketplaceApiApi.getConnectionApi,
    [MarketplaceApiApi.getSyncDirectionApi.key]: MarketplaceApiApi.getSyncDirectionApi,
    [MarketplaceApiApi.getSyncLogsApi.key]: MarketplaceApiApi.getSyncLogsApi,
    [MarketplaceApiApi.listConnectionsApi.key]: MarketplaceApiApi.listConnectionsApi,
    [MarketplaceApiApi.listPlatformsApi.key]: MarketplaceApiApi.listPlatformsApi,
    [MarketplaceApiApi.oauthAuthorizeApi.key]: MarketplaceApiApi.oauthAuthorizeApi,
    [MarketplaceApiApi.oauthCallbackApi.key]: MarketplaceApiApi.oauthCallbackApi,
    [MarketplaceApiApi.triggerSyncApi.key]: MarketplaceApiApi.triggerSyncApi,
    [MarketplaceApiApi.updateConnectionApi.key]: MarketplaceApiApi.updateConnectionApi,
    [MarketplaceApiApi.updateSyncDirectionApi.key]: MarketplaceApiApi.updateSyncDirectionApi,
    [MarketplaceApiApi.webhookReceiverApi.key]: MarketplaceApiApi.webhookReceiverApi,
    [NotificationsApi.deleteNotification.key]: NotificationsApi.deleteNotification,
    [NotificationsApi.listNotifications.key]: NotificationsApi.listNotifications,
    [NotificationsApi.markAllRead.key]: NotificationsApi.markAllRead,
    [NotificationsApi.markAsRead.key]: NotificationsApi.markAsRead,
    [NotificationsApi.unreadCount.key]: NotificationsApi.unreadCount,
    [OffenlegungApi.offenlegungApi.key]: OffenlegungApi.offenlegungApi,
    [OnlineshopApi.getSmtpConfigApi.key]: OnlineshopApi.getSmtpConfigApi,
    [OnlineshopApi.saveSmtpConfigApi.key]: OnlineshopApi.saveSmtpConfigApi,
    [OrderApi.addOrderTags.key]: OrderApi.addOrderTags,
    [OrderApi.findOrderByExternalRef.key]: OrderApi.findOrderByExternalRef,
    [OrderApi.getOrder.key]: OrderApi.getOrder,
    [OrderApi.getOrders.key]: OrderApi.getOrders,
    [OrderApi.patchOrder.key]: OrderApi.patchOrder,
    [OrderApi.replaceOrderTags.key]: OrderApi.replaceOrderTags,
    [OrderApi.updateOrderState.key]: OrderApi.updateOrderState,
    [OrderConfirmationApi.createConfirmation.key]: OrderConfirmationApi.createConfirmation,
    [OrderConfirmationApi.deleteConfirmation.key]: OrderConfirmationApi.deleteConfirmation,
    [OrderConfirmationApi.downloadConfirmationPdf.key]: OrderConfirmationApi.downloadConfirmationPdf,
    [OrderConfirmationApi.getConfirmation.key]: OrderConfirmationApi.getConfirmation,
    [OrderConfirmationApi.listConfirmations.key]: OrderConfirmationApi.listConfirmations,
    [OrderConfirmationApi.orderconfirmationRestore.key]: OrderConfirmationApi.orderconfirmationRestore,
    [OrderConfirmationApi.pursueConfirmation.key]: OrderConfirmationApi.pursueConfirmation,
    [OssReportApi.ossReportApi.key]: OssReportApi.ossReportApi,
    [PackingApi.completePacking.key]: PackingApi.completePacking,
    [PackingApi.getPackingQueue.key]: PackingApi.getPackingQueue,
    [PackingApi.printDeliveryNote.key]: PackingApi.printDeliveryNote,
    [PackingApi.printLabel.key]: PackingApi.printLabel,
    [PackingApi.recordPackingVideo.key]: PackingApi.recordPackingVideo,
    [ParticipationApi.createParticipation.key]: ParticipationApi.createParticipation,
    [ParticipationApi.deleteParticipation.key]: ParticipationApi.deleteParticipation,
    [ParticipationApi.getParticipation.key]: ParticipationApi.getParticipation,
    [ParticipationApi.getParticipations.key]: ParticipationApi.getParticipations,
    [ParticipationApi.updateParticipation.key]: ParticipationApi.updateParticipation,
    [PaygapApi.paygapAuskunftApi.key]: PaygapApi.paygapAuskunftApi,
    [PaygapApi.paygapExportApi.key]: PaygapApi.paygapExportApi,
    [PaygapApi.paygapReportApi.key]: PaygapApi.paygapReportApi,
    [PaymentApi.createPayment.key]: PaymentApi.createPayment,
    [PaymentApi.deletePayment.key]: PaymentApi.deletePayment,
    [PaymentApi.getPayment.key]: PaymentApi.getPayment,
    [PaymentApi.getPayments.key]: PaymentApi.getPayments,
    [PaymentApi.paymentRestore.key]: PaymentApi.paymentRestore,
    [PaymentApi.updatePayment.key]: PaymentApi.updatePayment,
    [PaymentConditionApi.listPaymentConditionsApi.key]: PaymentConditionApi.listPaymentConditionsApi,
    [PaymentGatewayApi.createPaymentGatewayApi.key]: PaymentGatewayApi.createPaymentGatewayApi,
    [PaymentGatewayApi.deletePaymentGatewayApi.key]: PaymentGatewayApi.deletePaymentGatewayApi,
    [PaymentGatewayApi.listPaymentGatewaysApi.key]: PaymentGatewayApi.listPaymentGatewaysApi,
    [PaymentGatewayApi.oauthAuthorizeApi.key]: PaymentGatewayApi.oauthAuthorizeApi,
    [PaymentGatewayApi.oauthCallbackApi.key]: PaymentGatewayApi.oauthCallbackApi,
    [PaymentGatewayApi.updatePaymentGatewayApi.key]: PaymentGatewayApi.updatePaymentGatewayApi,
    [PayrollApi.payrollApprove.key]: PayrollApi.payrollApprove,
    [PayrollApi.payrollAutopay.key]: PayrollApi.payrollAutopay,
    [PayrollApi.payrollCalculate.key]: PayrollApi.payrollCalculate,
    [PayrollApi.payrollCreate.key]: PayrollApi.payrollCreate,
    [PayrollApi.payrollDelete.key]: PayrollApi.payrollDelete,
    [PayrollApi.payrollElsterExport.key]: PayrollApi.payrollElsterExport,
    [PayrollApi.payrollEmail.key]: PayrollApi.payrollEmail,
    [PayrollApi.payrollEntryPdf.key]: PayrollApi.payrollEntryPdf,
    [PayrollApi.payrollGet.key]: PayrollApi.payrollGet,
    [PayrollApi.payrollList.key]: PayrollApi.payrollList,
    [PayrollApi.payrollPay.key]: PayrollApi.payrollPay,
    [PayrollApi.payrollPdf.key]: PayrollApi.payrollPdf,
    [PayrollApi.payrollSummary.key]: PayrollApi.payrollSummary,
    [PayrollApi.payrollSvMeldungen.key]: PayrollApi.payrollSvMeldungen,
    [PeppolApi.peppolApi.key]: PeppolApi.peppolApi,
    [PlausibilityApi.plausibilityCheckApi.key]: PlausibilityApi.plausibilityCheckApi,
    [PosApi.posBilling.key]: PosApi.posBilling,
    [PosApi.posCreateOrder.key]: PosApi.posCreateOrder,
    [PosApi.posCreateRegister.key]: PosApi.posCreateRegister,
    [PosApi.posCreateTable.key]: PosApi.posCreateTable,
    [PosApi.posDisableRegister.key]: PosApi.posDisableRegister,
    [PosApi.posFreeTable.key]: PosApi.posFreeTable,
    [PosApi.posKasseClosing.key]: PosApi.posKasseClosing,
    [PosApi.posKasseEntries.key]: PosApi.posKasseEntries,
    [PosApi.posKasseExport.key]: PosApi.posKasseExport,
    [PosApi.posKassePayInOut.key]: PosApi.posKassePayInOut,
    [PosApi.posListOrders.key]: PosApi.posListOrders,
    [PosApi.posListProducts.key]: PosApi.posListProducts,
    [PosApi.posListRegisters.key]: PosApi.posListRegisters,
    [PosApi.posListTables.key]: PosApi.posListTables,
    [PosApi.posOrderPrint.key]: PosApi.posOrderPrint,
    [PosApi.posOrderReceipt.key]: PosApi.posOrderReceipt,
    [PosApi.posPayOrder.key]: PosApi.posPayOrder,
    [PosApi.posSumupCheckout.key]: PosApi.posSumupCheckout,
    [PostingCategoryApi.createPostingCategory.key]: PostingCategoryApi.createPostingCategory,
    [PostingCategoryApi.deletePostingCategory.key]: PostingCategoryApi.deletePostingCategory,
    [PostingCategoryApi.listPostingCategories.key]: PostingCategoryApi.listPostingCategories,
    [PostingCategoryApi.seedPostingCategories.key]: PostingCategoryApi.seedPostingCategories,
    [PostingCategoryApi.updatePostingCategory.key]: PostingCategoryApi.updatePostingCategory,
    [PriceTierApi.createPriceTier.key]: PriceTierApi.createPriceTier,
    [PriceTierApi.deletePriceTier.key]: PriceTierApi.deletePriceTier,
    [PriceTierApi.getPriceTier.key]: PriceTierApi.getPriceTier,
    [PriceTierApi.getResolvedPrice.key]: PriceTierApi.getResolvedPrice,
    [PriceTierApi.listPriceTiers.key]: PriceTierApi.listPriceTiers,
    [PriceTierApi.updatePriceTier.key]: PriceTierApi.updatePriceTier,
    [ProductApi.createProductApi.key]: ProductApi.createProductApi,
    [ProductApi.deleteProductApi.key]: ProductApi.deleteProductApi,
    [ProductApi.getProductApi.key]: ProductApi.getProductApi,
    [ProductApi.getProductStockApi.key]: ProductApi.getProductStockApi,
    [ProductApi.getProductsApi.key]: ProductApi.getProductsApi,
    [ProductApi.listLowStockProductsApi.key]: ProductApi.listLowStockProductsApi,
    [ProductApi.productRestore.key]: ProductApi.productRestore,
    [ProductApi.updateProductApi.key]: ProductApi.updateProductApi,
    [ProductApi.updateProductStockApi.key]: ProductApi.updateProductStockApi,
    [ProductAttributeApi.createProductAttribute.key]: ProductAttributeApi.createProductAttribute,
    [ProductAttributeApi.deleteProductAttribute.key]: ProductAttributeApi.deleteProductAttribute,
    [ProductAttributeApi.getProductAttribute.key]: ProductAttributeApi.getProductAttribute,
    [ProductAttributeApi.listProductAttributes.key]: ProductAttributeApi.listProductAttributes,
    [ProductAttributeApi.updateProductAttribute.key]: ProductAttributeApi.updateProductAttribute,
    [ProductCategoryApi.createProductCategory.key]: ProductCategoryApi.createProductCategory,
    [ProductCategoryApi.deleteProductCategory.key]: ProductCategoryApi.deleteProductCategory,
    [ProductCategoryApi.getProductCategory.key]: ProductCategoryApi.getProductCategory,
    [ProductCategoryApi.listProductCategories.key]: ProductCategoryApi.listProductCategories,
    [ProductCategoryApi.updateProductCategory.key]: ProductCategoryApi.updateProductCategory,
    [ProductVariantApi.createProductVariant.key]: ProductVariantApi.createProductVariant,
    [ProductVariantApi.deleteProductVariant.key]: ProductVariantApi.deleteProductVariant,
    [ProductVariantApi.generateProductVariants.key]: ProductVariantApi.generateProductVariants,
    [ProductVariantApi.getProductVariant.key]: ProductVariantApi.getProductVariant,
    [ProductVariantApi.listProductVariants.key]: ProductVariantApi.listProductVariants,
    [ProductVariantApi.updateProductVariant.key]: ProductVariantApi.updateProductVariant,
    [ProductionOrderApi.createProductionOrder.key]: ProductionOrderApi.createProductionOrder,
    [ProductionOrderApi.deleteProductionOrder.key]: ProductionOrderApi.deleteProductionOrder,
    [ProductionOrderApi.getProductionOrder.key]: ProductionOrderApi.getProductionOrder,
    [ProductionOrderApi.listProductionOrders.key]: ProductionOrderApi.listProductionOrders,
    [ProductionOrderApi.productionOrderCosting.key]: ProductionOrderApi.productionOrderCosting,
    [ProductionOrderApi.updateProductionOrder.key]: ProductionOrderApi.updateProductionOrder,
    [ProductionOrderApi.updateProductionOrderStatus.key]: ProductionOrderApi.updateProductionOrderStatus,
    [ProformaInvoiceApi.convertProformaToInvoice.key]: ProformaInvoiceApi.convertProformaToInvoice,
    [ProformaInvoiceApi.createProformaInvoice.key]: ProformaInvoiceApi.createProformaInvoice,
    [ProformaInvoiceApi.deleteProformaInvoice.key]: ProformaInvoiceApi.deleteProformaInvoice,
    [ProformaInvoiceApi.getProformaInvoice.key]: ProformaInvoiceApi.getProformaInvoice,
    [ProformaInvoiceApi.listProformaInvoices.key]: ProformaInvoiceApi.listProformaInvoices,
    [ProformaInvoiceApi.updateProformaInvoice.key]: ProformaInvoiceApi.updateProformaInvoice,
    [ProposeAssignmentsApi.proposeAssignmentsApi.key]: ProposeAssignmentsApi.proposeAssignmentsApi,
    [PublicReturnsApi.getPublicReturnStatus.key]: PublicReturnsApi.getPublicReturnStatus,
    [PublicReturnsApi.listPublicReturns.key]: PublicReturnsApi.listPublicReturns,
    [PublicReturnsApi.requestPublicReturn.key]: PublicReturnsApi.requestPublicReturn,
    [PurchaseOrderApi.createPurchaseOrder.key]: PurchaseOrderApi.createPurchaseOrder,
    [PurchaseOrderApi.deletePurchaseOrder.key]: PurchaseOrderApi.deletePurchaseOrder,
    [PurchaseOrderApi.getPurchaseOrder.key]: PurchaseOrderApi.getPurchaseOrder,
    [PurchaseOrderApi.listPurchaseOrders.key]: PurchaseOrderApi.listPurchaseOrders,
    [PurchaseOrderApi.matchInvoice.key]: PurchaseOrderApi.matchInvoice,
    [PurchaseOrderApi.updatePurchaseOrder.key]: PurchaseOrderApi.updatePurchaseOrder,
    [PurchaseOrderApi.updatePurchaseOrderStatus.key]: PurchaseOrderApi.updatePurchaseOrderStatus,
    [QuotationApi.createQuotation.key]: QuotationApi.createQuotation,
    [QuotationApi.deleteQuotation.key]: QuotationApi.deleteQuotation,
    [QuotationApi.downloadQuotationPdf.key]: QuotationApi.downloadQuotationPdf,
    [QuotationApi.getQuotation.key]: QuotationApi.getQuotation,
    [QuotationApi.listQuotations.key]: QuotationApi.listQuotations,
    [QuotationApi.pursueQuotation.key]: QuotationApi.pursueQuotation,
    [QuotationApi.quotationRestore.key]: QuotationApi.quotationRestore,
    [QuotationApi.updateQuotation.key]: QuotationApi.updateQuotation,
    [RecurringTemplateApi.createRecurringTemplate.key]: RecurringTemplateApi.createRecurringTemplate,
    [RecurringTemplateApi.deleteRecurringTemplate.key]: RecurringTemplateApi.deleteRecurringTemplate,
    [RecurringTemplateApi.getRecurringTemplate.key]: RecurringTemplateApi.getRecurringTemplate,
    [RecurringTemplateApi.listRecurringTemplates.key]: RecurringTemplateApi.listRecurringTemplates,
    [ReorderProposalApi.applyReorderProposal.key]: ReorderProposalApi.applyReorderProposal,
    [ReorderProposalApi.getReorderProposal.key]: ReorderProposalApi.getReorderProposal,
    [ReplenishmentApi.applyReplenishments.key]: ReplenishmentApi.applyReplenishments,
    [ReplenishmentApi.getReplenishments.key]: ReplenishmentApi.getReplenishments,
    [ReportsApi.bilanzReportApi.key]: ReportsApi.bilanzReportApi,
    [ReportsApi.guvReportApi.key]: ReportsApi.guvReportApi,
    [ReportsApi.kontenansichtReportApi.key]: ReportsApi.kontenansichtReportApi,
    [ReportsApi.umsatzsteuerReportApi.key]: ReportsApi.umsatzsteuerReportApi,
    [ReturnOrderApi.createReturnOrder.key]: ReturnOrderApi.createReturnOrder,
    [ReturnOrderApi.deleteReturnOrder.key]: ReturnOrderApi.deleteReturnOrder,
    [ReturnOrderApi.getReturnOrder.key]: ReturnOrderApi.getReturnOrder,
    [ReturnOrderApi.listReturnOrders.key]: ReturnOrderApi.listReturnOrders,
    [ReturnOrderApi.returnLogisticsQueue.key]: ReturnOrderApi.returnLogisticsQueue,
    [ReturnOrderApi.returnLogisticsSummary.key]: ReturnOrderApi.returnLogisticsSummary,
    [ReturnOrderApi.updateReturnOrder.key]: ReturnOrderApi.updateReturnOrder,
    [ReturnOrderApi.updateReturnOrderStatus.key]: ReturnOrderApi.updateReturnOrderStatus,
    [RfqApi.convertRfq.key]: RfqApi.convertRfq,
    [RfqApi.createRfq.key]: RfqApi.createRfq,
    [RfqApi.deleteRfq.key]: RfqApi.deleteRfq,
    [RfqApi.getRfq.key]: RfqApi.getRfq,
    [RfqApi.listRfqs.key]: RfqApi.listRfqs,
    [RfqApi.updateRfq.key]: RfqApi.updateRfq,
    [RfqApi.updateRfqStatus.key]: RfqApi.updateRfqStatus,
    [SearchApi.globalSearch.key]: SearchApi.globalSearch,
    [SearchApi.myPermissions.key]: SearchApi.myPermissions,
    [ServiceAssignmentApi.createServiceAssignment.key]: ServiceAssignmentApi.createServiceAssignment,
    [ServiceAssignmentApi.deleteServiceAssignment.key]: ServiceAssignmentApi.deleteServiceAssignment,
    [ServiceAssignmentApi.getServiceAssignment.key]: ServiceAssignmentApi.getServiceAssignment,
    [ServiceAssignmentApi.getServiceAssignments.key]: ServiceAssignmentApi.getServiceAssignments,
    [ServiceAssignmentApi.updateServiceAssignment.key]: ServiceAssignmentApi.updateServiceAssignment,
    [ServiceJobApi.createServiceJob.key]: ServiceJobApi.createServiceJob,
    [ServiceJobApi.deleteServiceJob.key]: ServiceJobApi.deleteServiceJob,
    [ServiceJobApi.getServiceJob.key]: ServiceJobApi.getServiceJob,
    [ServiceJobApi.getServiceJobs.key]: ServiceJobApi.getServiceJobs,
    [ServiceJobApi.updateServiceJob.key]: ServiceJobApi.updateServiceJob,
    [ShareholderApi.createShareholder.key]: ShareholderApi.createShareholder,
    [ShareholderApi.deleteShareholder.key]: ShareholderApi.deleteShareholder,
    [ShareholderApi.getShareholder.key]: ShareholderApi.getShareholder,
    [ShareholderApi.getShareholders.key]: ShareholderApi.getShareholders,
    [ShareholderApi.updateShareholder.key]: ShareholderApi.updateShareholder,
    [ShipmentApi.createShipment.key]: ShipmentApi.createShipment,
    [ShipmentApi.createShipmentFromOrder.key]: ShipmentApi.createShipmentFromOrder,
    [ShipmentApi.deleteShipment.key]: ShipmentApi.deleteShipment,
    [ShipmentApi.getShipment.key]: ShipmentApi.getShipment,
    [ShipmentApi.listShipments.key]: ShipmentApi.listShipments,
    [ShipmentApi.trackOrderPublic.key]: ShipmentApi.trackOrderPublic,
    [ShipmentApi.trackShipmentApi.key]: ShipmentApi.trackShipmentApi,
    [ShipmentApi.updateShipmentStatus.key]: ShipmentApi.updateShipmentStatus,
    [ShippingApi.getCredentialsApi.key]: ShippingApi.getCredentialsApi,
    [ShippingApi.getRatesApi.key]: ShippingApi.getRatesApi,
    [ShippingApi.listProvidersApi.key]: ShippingApi.listProvidersApi,
    [ShippingApi.saveCredentialsApi.key]: ShippingApi.saveCredentialsApi,
    [ShippingRuleApi.createShippingRule.key]: ShippingRuleApi.createShippingRule,
    [ShippingRuleApi.deleteShippingRule.key]: ShippingRuleApi.deleteShippingRule,
    [ShippingRuleApi.getShippingRule.key]: ShippingRuleApi.getShippingRule,
    [ShippingRuleApi.listShippingRules.key]: ShippingRuleApi.listShippingRules,
    [ShippingRuleApi.updateShippingRule.key]: ShippingRuleApi.updateShippingRule,
    [ShippingThresholdApi.createShippingThreshold.key]: ShippingThresholdApi.createShippingThreshold,
    [ShippingThresholdApi.deleteShippingThreshold.key]: ShippingThresholdApi.deleteShippingThreshold,
    [ShippingThresholdApi.getDeliverable.key]: ShippingThresholdApi.getDeliverable,
    [ShippingThresholdApi.getShippingThreshold.key]: ShippingThresholdApi.getShippingThreshold,
    [ShippingThresholdApi.listShippingThresholds.key]: ShippingThresholdApi.listShippingThresholds,
    [ShippingThresholdApi.updateShippingThreshold.key]: ShippingThresholdApi.updateShippingThreshold,
    [ShopApi.shopEditorSave.key]: ShopApi.shopEditorSave,
    [SilentPartnerApi.createSilentPartner.key]: SilentPartnerApi.createSilentPartner,
    [SilentPartnerApi.deleteSilentPartner.key]: SilentPartnerApi.deleteSilentPartner,
    [SilentPartnerApi.getSilentPartner.key]: SilentPartnerApi.getSilentPartner,
    [SilentPartnerApi.getSilentPartners.key]: SilentPartnerApi.getSilentPartners,
    [SilentPartnerApi.updateSilentPartner.key]: SilentPartnerApi.updateSilentPartner,
    [StilleApi.stilleExportApi.key]: StilleApi.stilleExportApi,
    [StilleApi.stilleReportApi.key]: StilleApi.stilleReportApi,
    [StockMovementApi.getStockMovement.key]: StockMovementApi.getStockMovement,
    [StockMovementApi.listStockMovements.key]: StockMovementApi.listStockMovements,
    [StockTransferApi.createStockTransfer.key]: StockTransferApi.createStockTransfer,
    [StockTransferApi.deleteStockTransfer.key]: StockTransferApi.deleteStockTransfer,
    [StockTransferApi.getStockTransfer.key]: StockTransferApi.getStockTransfer,
    [StockTransferApi.listStockTransfers.key]: StockTransferApi.listStockTransfers,
    [StockTransferApi.updateStockTransferStatus.key]: StockTransferApi.updateStockTransferStatus,
    [SuitabilityApi.shippingSuitabilityApi.key]: SuitabilityApi.shippingSuitabilityApi,
    [SupplierConditionApi.createSupplierCondition.key]: SupplierConditionApi.createSupplierCondition,
    [SupplierConditionApi.deleteSupplierCondition.key]: SupplierConditionApi.deleteSupplierCondition,
    [SupplierConditionApi.getSupplierCondition.key]: SupplierConditionApi.getSupplierCondition,
    [SupplierConditionApi.listSupplierConditions.key]: SupplierConditionApi.listSupplierConditions,
    [SupplierConditionApi.updateSupplierCondition.key]: SupplierConditionApi.updateSupplierCondition,
    [SupplierInvoiceApi.createSupplierInvoice.key]: SupplierInvoiceApi.createSupplierInvoice,
    [SupplierInvoiceApi.deleteSupplierInvoice.key]: SupplierInvoiceApi.deleteSupplierInvoice,
    [SupplierInvoiceApi.getSupplierInvoice.key]: SupplierInvoiceApi.getSupplierInvoice,
    [SupplierInvoiceApi.listSupplierInvoices.key]: SupplierInvoiceApi.listSupplierInvoices,
    [SupplierInvoiceApi.updateSupplierInvoice.key]: SupplierInvoiceApi.updateSupplierInvoice,
    [SupplierInvoiceApi.updateSupplierInvoiceStatus.key]: SupplierInvoiceApi.updateSupplierInvoiceStatus,
    [SupportChannelApi.createChannelApi.key]: SupportChannelApi.createChannelApi,
    [SupportChannelApi.deleteChannelApi.key]: SupportChannelApi.deleteChannelApi,
    [SupportChannelApi.listChannelsApi.key]: SupportChannelApi.listChannelsApi,
    [SupportChannelApi.updateChannelApi.key]: SupportChannelApi.updateChannelApi,
    [SupportTicketApi.createTicketApi.key]: SupportTicketApi.createTicketApi,
    [SupportTicketApi.deleteTicketApi.key]: SupportTicketApi.deleteTicketApi,
    [SupportTicketApi.getTicketApi.key]: SupportTicketApi.getTicketApi,
    [SupportTicketApi.listTicketsApi.key]: SupportTicketApi.listTicketsApi,
    [SupportTicketApi.updateTicketApi.key]: SupportTicketApi.updateTicketApi,
    [TaxApi.createTaxRate.key]: TaxApi.createTaxRate,
    [TaxApi.deleteTaxRate.key]: TaxApi.deleteTaxRate,
    [TaxApi.listTaxRates.key]: TaxApi.listTaxRates,
    [TaxApi.updateTaxRate.key]: TaxApi.updateTaxRate,
    [TenantSettingsApi.getTenantSettings.key]: TenantSettingsApi.getTenantSettings,
    [TenantSettingsApi.updateTenantSettings.key]: TenantSettingsApi.updateTenantSettings,
    [TicketMessageApi.listMessagesApi.key]: TicketMessageApi.listMessagesApi,
    [TicketMessageApi.sendMessageApi.key]: TicketMessageApi.sendMessageApi,
    [TimeEntriesApi.clockInTimeEntry.key]: TimeEntriesApi.clockInTimeEntry,
    [TimeEntriesApi.clockOutTimeEntry.key]: TimeEntriesApi.clockOutTimeEntry,
    [TimeEntriesApi.getLaborCosts.key]: TimeEntriesApi.getLaborCosts,
    [TimeEntriesApi.listTimeEntries.key]: TimeEntriesApi.listTimeEntries,
    [TrainingAssignmentApi.createTrainingAssignment.key]: TrainingAssignmentApi.createTrainingAssignment,
    [TrainingAssignmentApi.deleteTrainingAssignment.key]: TrainingAssignmentApi.deleteTrainingAssignment,
    [TrainingAssignmentApi.getTrainingAssignment.key]: TrainingAssignmentApi.getTrainingAssignment,
    [TrainingAssignmentApi.getTrainingAssignments.key]: TrainingAssignmentApi.getTrainingAssignments,
    [TrainingAssignmentApi.updateTrainingAssignment.key]: TrainingAssignmentApi.updateTrainingAssignment,
    [TrainingsApi.getMyTrainings.key]: TrainingsApi.getMyTrainings,
    [TrainingsApi.getTrainingContent.key]: TrainingsApi.getTrainingContent,
    [TrainingsApi.getTrainingOverview.key]: TrainingsApi.getTrainingOverview,
    [TrainingsApi.submitTrainingResult.key]: TrainingsApi.submitTrainingResult,
    [UserApi.changePassword.key]: UserApi.changePassword,
    [UserApi.createTeam.key]: UserApi.createTeam,
    [UserApi.generateApiKey.key]: UserApi.generateApiKey,
    [UserApi.inviteUser.key]: UserApi.inviteUser,
    [UserApi.listTeams.key]: UserApi.listTeams,
    [UserApi.removeUserFromOrg.key]: UserApi.removeUserFromOrg,
    [UserApi.updateProfile.key]: UserApi.updateProfile,
    [UserApi.userProfile.key]: UserApi.userProfile,
    [UserApi.userTenants.key]: UserApi.userTenants,
    [UserManagementApi.getUser.key]: UserManagementApi.getUser,
    [UserManagementApi.listUsers.key]: UserManagementApi.listUsers,
    [UserManagementApi.removeUser.key]: UserManagementApi.removeUser,
    [UserManagementApi.updateUserPermissions.key]: UserManagementApi.updateUserPermissions,
    [UserManagementApi.updateUserRole.key]: UserManagementApi.updateUserRole,
    [UstvaApi.jahresustApi.key]: UstvaApi.jahresustApi,
    [UstvaApi.ustvaApi.key]: UstvaApi.ustvaApi,
    [VoucherApi.createVoucher.key]: VoucherApi.createVoucher,
    [VoucherApi.deleteVoucher.key]: VoucherApi.deleteVoucher,
    [VoucherApi.getVoucher.key]: VoucherApi.getVoucher,
    [VoucherApi.listVouchers.key]: VoucherApi.listVouchers,
    [VoucherApi.updateVoucher.key]: VoucherApi.updateVoucher,
    [VoucherApi.voucherRestore.key]: VoucherApi.voucherRestore,
    [WarehouseApi.createWarehouse.key]: WarehouseApi.createWarehouse,
    [WarehouseApi.deleteWarehouse.key]: WarehouseApi.deleteWarehouse,
    [WarehouseApi.getWarehouse.key]: WarehouseApi.getWarehouse,
    [WarehouseApi.listWarehouses.key]: WarehouseApi.listWarehouses,
    [WarehouseApi.updateWarehouse.key]: WarehouseApi.updateWarehouse,
    [WarehouseStockApi.createWarehouseStock.key]: WarehouseStockApi.createWarehouseStock,
    [WarehouseStockApi.deleteWarehouseStock.key]: WarehouseStockApi.deleteWarehouseStock,
    [WarehouseStockApi.listWarehouseStock.key]: WarehouseStockApi.listWarehouseStock,
    [WarehouseStockApi.updateWarehouseStock.key]: WarehouseStockApi.updateWarehouseStock,
    [WebhooksApi.createSubscription.key]: WebhooksApi.createSubscription,
    [WebhooksApi.deleteSubscription.key]: WebhooksApi.deleteSubscription,
    [WebhooksApi.emitApi.key]: WebhooksApi.emitApi,
    [WebhooksApi.listEvent.key]: WebhooksApi.listEvent,
    [WebhooksApi.listSubscriptions.key]: WebhooksApi.listSubscriptions,
    [WebhooksApi.updateSubscription.key]: WebhooksApi.updateSubscription,
    [WorkflowsApi.listWorkflowsApi.key]: WorkflowsApi.listWorkflowsApi,
    [WorkflowsApi.setWorkflowEnabledApi.key]: WorkflowsApi.setWorkflowEnabledApi,
    [ZugferdApi.generateZugferdApi.key]: ZugferdApi.generateZugferdApi,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: createMiddleware(value)} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
