const utils = require('../utils/utils');
const AnyType = require('../models/AnyType');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}account_holder`,
                label: `[${labelPrefix}account_holder]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}acquisition_cost`,
                label: `[${labelPrefix}acquisition_cost]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}address_supplement`,
                label: `[${labelPrefix}address_supplement]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}attention`,
                label: `[${labelPrefix}attention]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}bank_name`,
                label: `[${labelPrefix}bank_name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}bic`,
                label: `[${labelPrefix}bic]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}buyer_reference`,
                label: `[${labelPrefix}buyer_reference]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}category`,
                label: `[${labelPrefix}category]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificate_authority`,
                label: `[${labelPrefix}certificate_authority]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificate_number`,
                label: `[${labelPrefix}certificate_number]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificate_paragraph`,
                label: `[${labelPrefix}certificate_paragraph]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificate_valid_until`,
                label: `[${labelPrefix}certificate_valid_until]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}city`,
                label: `[${labelPrefix}city]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}company_name`,
                label: `[${labelPrefix}company_name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}contact_id`,
                label: `[${labelPrefix}contact_id]`,
                required: true,
                type: 'string',
            },
            ....fields(`${keyPrefix}contact_persons`, isInput),
            {
                key: `${keyPrefix}contact_type`,
                label: `[${labelPrefix}contact_type]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}country`,
                label: `[${labelPrefix}country]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}created_at`,
                label: `[${labelPrefix}created_at]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}credit_limit`,
                label: `[${labelPrefix}credit_limit]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}creditor_account_skr03`,
                label: `[${labelPrefix}creditor_account_skr03]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}creditor_account_skr04`,
                label: `[${labelPrefix}creditor_account_skr04]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currency`,
                label: `[${labelPrefix}currency]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customer_number`,
                label: `[${labelPrefix}customer_number]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}debitor_account_skr03`,
                label: `[${labelPrefix}debitor_account_skr03]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}debitor_account_skr04`,
                label: `[${labelPrefix}debitor_account_skr04]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}default_debitor_number`,
                label: `[${labelPrefix}default_debitor_number]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}delivery_block`,
                label: `[${labelPrefix}delivery_block]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}department`,
                label: `[${labelPrefix}department]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}discount_days`,
                label: `[${labelPrefix}discount_days]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}discount_percentage`,
                label: `[${labelPrefix}discount_percentage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}donation_receipt_eligible`,
                label: `[${labelPrefix}donation_receipt_eligible]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}email`,
                label: `[${labelPrefix}email]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}external_id`,
                label: `[${labelPrefix}external_id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fax`,
                label: `[${labelPrefix}fax]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}iban`,
                label: `[${labelPrefix}iban]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}industry`,
                label: `[${labelPrefix}industry]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}is_active`,
                label: `[${labelPrefix}is_active]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}is_member`,
                label: `[${labelPrefix}is_member]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}is_nonprofit`,
                label: `[${labelPrefix}is_nonprofit]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}last_contact_date`,
                label: `[${labelPrefix}last_contact_date]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}last_purchase_date`,
                label: `[${labelPrefix}last_purchase_date]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}leitweg_id`,
                label: `[${labelPrefix}leitweg_id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lifetime_value`,
                label: `[${labelPrefix}lifetime_value]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mandate_date`,
                label: `[${labelPrefix}mandate_date]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mandate_reference`,
                label: `[${labelPrefix}mandate_reference]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}marketing_consent`,
                label: `[${labelPrefix}marketing_consent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}marketing_consent_at`,
                label: `[${labelPrefix}marketing_consent_at]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}marketing_consent_source`,
                label: `[${labelPrefix}marketing_consent_source]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mobile`,
                label: `[${labelPrefix}mobile]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}next_contact_date`,
                label: `[${labelPrefix}next_contact_date]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}notes`,
                label: `[${labelPrefix}notes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}opening_balance`,
                label: `[${labelPrefix}opening_balance]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}opening_balance_date`,
                label: `[${labelPrefix}opening_balance_date]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}order_reference`,
                label: `[${labelPrefix}order_reference]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}payment_block`,
                label: `[${labelPrefix}payment_block]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}payment_grace_period_days`,
                label: `[${labelPrefix}payment_grace_period_days]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}payment_methods`,
                label: `[${labelPrefix}payment_methods]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}payment_terms`,
                label: `[${labelPrefix}payment_terms]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}phone`,
                label: `[${labelPrefix}phone]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}rating`,
                label: `[${labelPrefix}rating]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}sales_representative`,
                label: `[${labelPrefix}sales_representative]`,
                type: 'string',
            },
            ....fields(`${keyPrefix}social_media`, isInput),
            {
                key: `${keyPrefix}source`,
                label: `[${labelPrefix}source]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}state`,
                label: `[${labelPrefix}state]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}street`,
                label: `[${labelPrefix}street]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}street_number`,
                label: `[${labelPrefix}street_number]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}supplier_number`,
                label: `[${labelPrefix}supplier_number]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tags`,
                label: `[${labelPrefix}tags]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}tax_country`,
                label: `[${labelPrefix}tax_country]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tax_number`,
                label: `[${labelPrefix}tax_number]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tax_office`,
                label: `[${labelPrefix}tax_office]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}total_invoices`,
                label: `[${labelPrefix}total_invoices]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}total_revenue`,
                label: `[${labelPrefix}total_revenue]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}updated_at`,
                label: `[${labelPrefix}updated_at]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}vat_id`,
                label: `[${labelPrefix}vat_id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}vat_id_validated`,
                label: `[${labelPrefix}vat_id_validated]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}vat_id_validation_date`,
                label: `[${labelPrefix}vat_id_validation_date]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}website`,
                label: `[${labelPrefix}website]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}zip`,
                label: `[${labelPrefix}zip]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'account_holder': bundle.inputData?.[`${keyPrefix}account_holder`],
            'acquisition_cost': bundle.inputData?.[`${keyPrefix}acquisition_cost`],
            'address_supplement': bundle.inputData?.[`${keyPrefix}address_supplement`],
            'attention': bundle.inputData?.[`${keyPrefix}attention`],
            'bank_name': bundle.inputData?.[`${keyPrefix}bank_name`],
            'bic': bundle.inputData?.[`${keyPrefix}bic`],
            'buyer_reference': bundle.inputData?.[`${keyPrefix}buyer_reference`],
            'category': bundle.inputData?.[`${keyPrefix}category`],
            'certificate_authority': bundle.inputData?.[`${keyPrefix}certificate_authority`],
            'certificate_number': bundle.inputData?.[`${keyPrefix}certificate_number`],
            'certificate_paragraph': bundle.inputData?.[`${keyPrefix}certificate_paragraph`],
            'certificate_valid_until': bundle.inputData?.[`${keyPrefix}certificate_valid_until`],
            'city': bundle.inputData?.[`${keyPrefix}city`],
            'company_name': bundle.inputData?.[`${keyPrefix}company_name`],
            'contact_id': bundle.inputData?.[`${keyPrefix}contact_id`],
            'contact_persons': utils.removeIfEmpty(.mapping(bundle, `${keyPrefix}contact_persons`)),
            'contact_type': bundle.inputData?.[`${keyPrefix}contact_type`],
            'country': bundle.inputData?.[`${keyPrefix}country`],
            'created_at': bundle.inputData?.[`${keyPrefix}created_at`],
            'credit_limit': bundle.inputData?.[`${keyPrefix}credit_limit`],
            'creditor_account_skr03': bundle.inputData?.[`${keyPrefix}creditor_account_skr03`],
            'creditor_account_skr04': bundle.inputData?.[`${keyPrefix}creditor_account_skr04`],
            'currency': bundle.inputData?.[`${keyPrefix}currency`],
            'customer_number': bundle.inputData?.[`${keyPrefix}customer_number`],
            'debitor_account_skr03': bundle.inputData?.[`${keyPrefix}debitor_account_skr03`],
            'debitor_account_skr04': bundle.inputData?.[`${keyPrefix}debitor_account_skr04`],
            'default_debitor_number': bundle.inputData?.[`${keyPrefix}default_debitor_number`],
            'delivery_block': bundle.inputData?.[`${keyPrefix}delivery_block`],
            'department': bundle.inputData?.[`${keyPrefix}department`],
            'discount_days': bundle.inputData?.[`${keyPrefix}discount_days`],
            'discount_percentage': bundle.inputData?.[`${keyPrefix}discount_percentage`],
            'donation_receipt_eligible': bundle.inputData?.[`${keyPrefix}donation_receipt_eligible`],
            'email': bundle.inputData?.[`${keyPrefix}email`],
            'external_id': bundle.inputData?.[`${keyPrefix}external_id`],
            'fax': bundle.inputData?.[`${keyPrefix}fax`],
            'iban': bundle.inputData?.[`${keyPrefix}iban`],
            'industry': bundle.inputData?.[`${keyPrefix}industry`],
            'is_active': bundle.inputData?.[`${keyPrefix}is_active`],
            'is_member': bundle.inputData?.[`${keyPrefix}is_member`],
            'is_nonprofit': bundle.inputData?.[`${keyPrefix}is_nonprofit`],
            'last_contact_date': bundle.inputData?.[`${keyPrefix}last_contact_date`],
            'last_purchase_date': bundle.inputData?.[`${keyPrefix}last_purchase_date`],
            'leitweg_id': bundle.inputData?.[`${keyPrefix}leitweg_id`],
            'lifetime_value': bundle.inputData?.[`${keyPrefix}lifetime_value`],
            'mandate_date': bundle.inputData?.[`${keyPrefix}mandate_date`],
            'mandate_reference': bundle.inputData?.[`${keyPrefix}mandate_reference`],
            'marketing_consent': bundle.inputData?.[`${keyPrefix}marketing_consent`],
            'marketing_consent_at': bundle.inputData?.[`${keyPrefix}marketing_consent_at`],
            'marketing_consent_source': bundle.inputData?.[`${keyPrefix}marketing_consent_source`],
            'mobile': bundle.inputData?.[`${keyPrefix}mobile`],
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'next_contact_date': bundle.inputData?.[`${keyPrefix}next_contact_date`],
            'notes': bundle.inputData?.[`${keyPrefix}notes`],
            'opening_balance': bundle.inputData?.[`${keyPrefix}opening_balance`],
            'opening_balance_date': bundle.inputData?.[`${keyPrefix}opening_balance_date`],
            'order_reference': bundle.inputData?.[`${keyPrefix}order_reference`],
            'payment_block': bundle.inputData?.[`${keyPrefix}payment_block`],
            'payment_grace_period_days': bundle.inputData?.[`${keyPrefix}payment_grace_period_days`],
            'payment_methods': bundle.inputData?.[`${keyPrefix}payment_methods`],
            'payment_terms': bundle.inputData?.[`${keyPrefix}payment_terms`],
            'phone': bundle.inputData?.[`${keyPrefix}phone`],
            'rating': bundle.inputData?.[`${keyPrefix}rating`],
            'sales_representative': bundle.inputData?.[`${keyPrefix}sales_representative`],
            'social_media': utils.removeIfEmpty(.mapping(bundle, `${keyPrefix}social_media`)),
            'source': bundle.inputData?.[`${keyPrefix}source`],
            'state': bundle.inputData?.[`${keyPrefix}state`],
            'street': bundle.inputData?.[`${keyPrefix}street`],
            'street_number': bundle.inputData?.[`${keyPrefix}street_number`],
            'supplier_number': bundle.inputData?.[`${keyPrefix}supplier_number`],
            'tags': bundle.inputData?.[`${keyPrefix}tags`],
            'tax_country': bundle.inputData?.[`${keyPrefix}tax_country`],
            'tax_number': bundle.inputData?.[`${keyPrefix}tax_number`],
            'tax_office': bundle.inputData?.[`${keyPrefix}tax_office`],
            'total_invoices': bundle.inputData?.[`${keyPrefix}total_invoices`],
            'total_revenue': bundle.inputData?.[`${keyPrefix}total_revenue`],
            'updated_at': bundle.inputData?.[`${keyPrefix}updated_at`],
            'vat_id': bundle.inputData?.[`${keyPrefix}vat_id`],
            'vat_id_validated': bundle.inputData?.[`${keyPrefix}vat_id_validated`],
            'vat_id_validation_date': bundle.inputData?.[`${keyPrefix}vat_id_validation_date`],
            'website': bundle.inputData?.[`${keyPrefix}website`],
            'zip': bundle.inputData?.[`${keyPrefix}zip`],
        }
    },
}
