const utils = require('../utils/utils');
const AnyType = require('../models/AnyType');
const ContactType = require('../models/ContactType');
const CountryCode = require('../models/CountryCode');
const SepaSequenceType = require('../models/SepaSequenceType');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}accountHolder`,
                label: `[${labelPrefix}accountHolder]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}acquisitionCost`,
                label: `[${labelPrefix}acquisitionCost]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressSupplement`,
                label: `[${labelPrefix}addressSupplement]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}attention`,
                label: `[${labelPrefix}attention]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}bankName`,
                label: `[${labelPrefix}bankName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}bic`,
                label: `[${labelPrefix}bic]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}buyerReference`,
                label: `[${labelPrefix}buyerReference]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}category`,
                label: `[${labelPrefix}category]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificateAuthority`,
                label: `[${labelPrefix}certificateAuthority]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificateNumber`,
                label: `[${labelPrefix}certificateNumber]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificateParagraph`,
                label: `[${labelPrefix}certificateParagraph]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certificateValidUntil`,
                label: `[${labelPrefix}certificateValidUntil]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}city`,
                label: `[${labelPrefix}city]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}companyName`,
                label: `[${labelPrefix}companyName]`,
                type: 'string',
            },
            ....fields(`${keyPrefix}contactPersons`, isInput),
            {
                key: `${keyPrefix}contactType`,
                ...ContactType.fields(`${keyPrefix}contactType`, isInput),
            },
            {
                key: `${keyPrefix}country`,
                ...CountryCode.fields(`${keyPrefix}country`, isInput),
            },
            {
                key: `${keyPrefix}creditLimit`,
                label: `[${labelPrefix}creditLimit]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}creditorAccountSkr03`,
                label: `[${labelPrefix}creditorAccountSkr03]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}creditorAccountSkr04`,
                label: `[${labelPrefix}creditorAccountSkr04]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currency`,
                label: `[${labelPrefix}currency]`,
                type: 'string',
            },
            ....fields(`${keyPrefix}customFields`, isInput),
            {
                key: `${keyPrefix}customerNumber`,
                label: `[${labelPrefix}customerNumber]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}debitorAccountSkr03`,
                label: `[${labelPrefix}debitorAccountSkr03]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}debitorAccountSkr04`,
                label: `[${labelPrefix}debitorAccountSkr04]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}defaultDebitorNumber`,
                label: `[${labelPrefix}defaultDebitorNumber]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}deliveryBlock`,
                label: `[${labelPrefix}deliveryBlock]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}department`,
                label: `[${labelPrefix}department]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}discountDays`,
                label: `[${labelPrefix}discountDays]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}discountPercentage`,
                label: `[${labelPrefix}discountPercentage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}donationReceiptEligible`,
                label: `[${labelPrefix}donationReceiptEligible]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}email`,
                label: `[${labelPrefix}email]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}externalId`,
                label: `[${labelPrefix}externalId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fax`,
                label: `[${labelPrefix}fax]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}iban`,
                label: `[${labelPrefix}iban]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}industry`,
                label: `[${labelPrefix}industry]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}isActive`,
                label: `[${labelPrefix}isActive]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isMember`,
                label: `[${labelPrefix}isMember]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNonprofit`,
                label: `[${labelPrefix}isNonprofit]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}lastContactDate`,
                label: `[${labelPrefix}lastContactDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastPurchaseDate`,
                label: `[${labelPrefix}lastPurchaseDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}leitwegId`,
                label: `[${labelPrefix}leitwegId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lifetimeValue`,
                label: `[${labelPrefix}lifetimeValue]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mandateDate`,
                label: `[${labelPrefix}mandateDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mandateReference`,
                label: `[${labelPrefix}mandateReference]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}marketingConsent`,
                label: `[${labelPrefix}marketingConsent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}marketingConsentAt`,
                label: `[${labelPrefix}marketingConsentAt]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}marketingConsentSource`,
                label: `[${labelPrefix}marketingConsentSource]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mobile`,
                label: `[${labelPrefix}mobile]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}nextContactDate`,
                label: `[${labelPrefix}nextContactDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}notes`,
                label: `[${labelPrefix}notes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}openingBalance`,
                label: `[${labelPrefix}openingBalance]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}openingBalanceDate`,
                label: `[${labelPrefix}openingBalanceDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}orderReference`,
                label: `[${labelPrefix}orderReference]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentBlock`,
                label: `[${labelPrefix}paymentBlock]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}paymentGracePeriodDays`,
                label: `[${labelPrefix}paymentGracePeriodDays]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}paymentMethods`,
                label: `[${labelPrefix}paymentMethods]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentTerms`,
                label: `[${labelPrefix}paymentTerms]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}phone`,
                label: `[${labelPrefix}phone]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}rating`,
                label: `[${labelPrefix}rating]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}salesRepresentative`,
                label: `[${labelPrefix}salesRepresentative]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}sepaBatchBooking`,
                label: `[${labelPrefix}sepaBatchBooking]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}sepaSequenceType`,
                ...SepaSequenceType.fields(`${keyPrefix}sepaSequenceType`, isInput),
            },
            ....fields(`${keyPrefix}socialMedia`, isInput),
            {
                key: `${keyPrefix}source`,
                label: `[${labelPrefix}source]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}state`,
                label: `[${labelPrefix}state]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}street`,
                label: `[${labelPrefix}street]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}streetNumber`,
                label: `[${labelPrefix}streetNumber]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}supplierNumber`,
                label: `[${labelPrefix}supplierNumber]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tags`,
                label: `[${labelPrefix}tags]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}taxCountry`,
                ...CountryCode.fields(`${keyPrefix}taxCountry`, isInput),
            },
            {
                key: `${keyPrefix}taxNumber`,
                label: `[${labelPrefix}taxNumber]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}taxOffice`,
                label: `[${labelPrefix}taxOffice]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalInvoices`,
                label: `[${labelPrefix}totalInvoices]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}totalRevenue`,
                label: `[${labelPrefix}totalRevenue]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}vatId`,
                label: `[${labelPrefix}vatId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}vatIdValidated`,
                label: `[${labelPrefix}vatIdValidated]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}vatIdValidationDate`,
                label: `[${labelPrefix}vatIdValidationDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}website`,
                label: `[${labelPrefix}website]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}zip`,
                label: `[${labelPrefix}zip]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'accountHolder': bundle.inputData?.[`${keyPrefix}accountHolder`],
            'acquisitionCost': bundle.inputData?.[`${keyPrefix}acquisitionCost`],
            'addressSupplement': bundle.inputData?.[`${keyPrefix}addressSupplement`],
            'attention': bundle.inputData?.[`${keyPrefix}attention`],
            'bankName': bundle.inputData?.[`${keyPrefix}bankName`],
            'bic': bundle.inputData?.[`${keyPrefix}bic`],
            'buyerReference': bundle.inputData?.[`${keyPrefix}buyerReference`],
            'category': bundle.inputData?.[`${keyPrefix}category`],
            'certificateAuthority': bundle.inputData?.[`${keyPrefix}certificateAuthority`],
            'certificateNumber': bundle.inputData?.[`${keyPrefix}certificateNumber`],
            'certificateParagraph': bundle.inputData?.[`${keyPrefix}certificateParagraph`],
            'certificateValidUntil': bundle.inputData?.[`${keyPrefix}certificateValidUntil`],
            'city': bundle.inputData?.[`${keyPrefix}city`],
            'companyName': bundle.inputData?.[`${keyPrefix}companyName`],
            'contactPersons': utils.removeIfEmpty(.mapping(bundle, `${keyPrefix}contactPersons`)),
            'contactType': bundle.inputData?.[`${keyPrefix}contactType`],
            'country': bundle.inputData?.[`${keyPrefix}country`],
            'creditLimit': bundle.inputData?.[`${keyPrefix}creditLimit`],
            'creditorAccountSkr03': bundle.inputData?.[`${keyPrefix}creditorAccountSkr03`],
            'creditorAccountSkr04': bundle.inputData?.[`${keyPrefix}creditorAccountSkr04`],
            'currency': bundle.inputData?.[`${keyPrefix}currency`],
            'customFields': utils.removeIfEmpty(.mapping(bundle, `${keyPrefix}customFields`)),
            'customerNumber': bundle.inputData?.[`${keyPrefix}customerNumber`],
            'debitorAccountSkr03': bundle.inputData?.[`${keyPrefix}debitorAccountSkr03`],
            'debitorAccountSkr04': bundle.inputData?.[`${keyPrefix}debitorAccountSkr04`],
            'defaultDebitorNumber': bundle.inputData?.[`${keyPrefix}defaultDebitorNumber`],
            'deliveryBlock': bundle.inputData?.[`${keyPrefix}deliveryBlock`],
            'department': bundle.inputData?.[`${keyPrefix}department`],
            'discountDays': bundle.inputData?.[`${keyPrefix}discountDays`],
            'discountPercentage': bundle.inputData?.[`${keyPrefix}discountPercentage`],
            'donationReceiptEligible': bundle.inputData?.[`${keyPrefix}donationReceiptEligible`],
            'email': bundle.inputData?.[`${keyPrefix}email`],
            'externalId': bundle.inputData?.[`${keyPrefix}externalId`],
            'fax': bundle.inputData?.[`${keyPrefix}fax`],
            'iban': bundle.inputData?.[`${keyPrefix}iban`],
            'industry': bundle.inputData?.[`${keyPrefix}industry`],
            'isActive': bundle.inputData?.[`${keyPrefix}isActive`],
            'isMember': bundle.inputData?.[`${keyPrefix}isMember`],
            'isNonprofit': bundle.inputData?.[`${keyPrefix}isNonprofit`],
            'lastContactDate': bundle.inputData?.[`${keyPrefix}lastContactDate`],
            'lastPurchaseDate': bundle.inputData?.[`${keyPrefix}lastPurchaseDate`],
            'leitwegId': bundle.inputData?.[`${keyPrefix}leitwegId`],
            'lifetimeValue': bundle.inputData?.[`${keyPrefix}lifetimeValue`],
            'mandateDate': bundle.inputData?.[`${keyPrefix}mandateDate`],
            'mandateReference': bundle.inputData?.[`${keyPrefix}mandateReference`],
            'marketingConsent': bundle.inputData?.[`${keyPrefix}marketingConsent`],
            'marketingConsentAt': bundle.inputData?.[`${keyPrefix}marketingConsentAt`],
            'marketingConsentSource': bundle.inputData?.[`${keyPrefix}marketingConsentSource`],
            'mobile': bundle.inputData?.[`${keyPrefix}mobile`],
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'nextContactDate': bundle.inputData?.[`${keyPrefix}nextContactDate`],
            'notes': bundle.inputData?.[`${keyPrefix}notes`],
            'openingBalance': bundle.inputData?.[`${keyPrefix}openingBalance`],
            'openingBalanceDate': bundle.inputData?.[`${keyPrefix}openingBalanceDate`],
            'orderReference': bundle.inputData?.[`${keyPrefix}orderReference`],
            'paymentBlock': bundle.inputData?.[`${keyPrefix}paymentBlock`],
            'paymentGracePeriodDays': bundle.inputData?.[`${keyPrefix}paymentGracePeriodDays`],
            'paymentMethods': bundle.inputData?.[`${keyPrefix}paymentMethods`],
            'paymentTerms': bundle.inputData?.[`${keyPrefix}paymentTerms`],
            'phone': bundle.inputData?.[`${keyPrefix}phone`],
            'rating': bundle.inputData?.[`${keyPrefix}rating`],
            'salesRepresentative': bundle.inputData?.[`${keyPrefix}salesRepresentative`],
            'sepaBatchBooking': bundle.inputData?.[`${keyPrefix}sepaBatchBooking`],
            'sepaSequenceType': bundle.inputData?.[`${keyPrefix}sepaSequenceType`],
            'socialMedia': utils.removeIfEmpty(.mapping(bundle, `${keyPrefix}socialMedia`)),
            'source': bundle.inputData?.[`${keyPrefix}source`],
            'state': bundle.inputData?.[`${keyPrefix}state`],
            'street': bundle.inputData?.[`${keyPrefix}street`],
            'streetNumber': bundle.inputData?.[`${keyPrefix}streetNumber`],
            'supplierNumber': bundle.inputData?.[`${keyPrefix}supplierNumber`],
            'tags': bundle.inputData?.[`${keyPrefix}tags`],
            'taxCountry': bundle.inputData?.[`${keyPrefix}taxCountry`],
            'taxNumber': bundle.inputData?.[`${keyPrefix}taxNumber`],
            'taxOffice': bundle.inputData?.[`${keyPrefix}taxOffice`],
            'totalInvoices': bundle.inputData?.[`${keyPrefix}totalInvoices`],
            'totalRevenue': bundle.inputData?.[`${keyPrefix}totalRevenue`],
            'vatId': bundle.inputData?.[`${keyPrefix}vatId`],
            'vatIdValidated': bundle.inputData?.[`${keyPrefix}vatIdValidated`],
            'vatIdValidationDate': bundle.inputData?.[`${keyPrefix}vatIdValidationDate`],
            'website': bundle.inputData?.[`${keyPrefix}website`],
            'zip': bundle.inputData?.[`${keyPrefix}zip`],
        }
    },
}
